trigger:
- master
- release/*

variables:
  MOZJPEG_VERSION: '3.3.1'
  MOZJPEG_VERSION_IDENTIFIER: 'v3.3.1'
  SrcDir: '$(System.DefaultWorkingDirectory)/src'
  solution: '$(SrcDir)/MozJpegSharp.sln'
  BuildConfiguration: 'Release'
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  RunTests: true

jobs:
- job: NBGV
  - task: DotNetCoreCLI@2
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . nbgv
    displayName: Install NBGV tool
  - script: nbgv cloud
    displayName: Set Version

- job: native_windows
  strategy:
    maxParallel: 2
    matrix:
      x64:
        BUILD_ARCH: x64
        PLATFORM: x64
        RID: win7-x64
      x86:
        BUILD_ARCH: x86
        PLATFORM: Win32
        RID: win7-x86
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
      %VCPKG_INSTALLATION_ROOT%\vcpkg version
      %VCPKG_INSTALLATION_ROOT%\vcpkg integrate install
      set VCPKG_BUILD_TYPE=release
      %VCPKG_INSTALLATION_ROOT%\vcpkg install mozjpeg:%BUILD_ARCH%-windows
    displayName: Install native dependencies
  - script: |
      mkdir %BUILD_ARTIFACTSTAGINGDIRECTORY%\mozjpeg\%RID%\bin\
      copy %VCPKG_INSTALLATION_ROOT%\installed\%BUILD_ARCH%-windows\tools\mozjpeg\*jpeg*.dll %BUILD_ARTIFACTSTAGINGDIRECTORY%\mozjpeg\%RID%\bin\
      copy %VCPKG_INSTALLATION_ROOT%\installed\%BUILD_ARCH%-windows\share\mozjpeg\copyright %BUILD_ARTIFACTSTAGINGDIRECTORY%\mozjpeg\%RID%\bin\mozjpeg.copyright
    displayName: 'Install'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/mozjpeg/'
      artifactName: 'mozjpeg' 
      publishLocation: 'Container'
    displayName: Publish

- job: native_macos
  pool:
    vmImage: 'macos10.15'
  variables:
    TARGET: x86_64-apple-darwin
    RID: osx-x64
  steps:
  - script: |
      brew install autoconf automake libtool pkg-config nasm
    displayName: Install autotools, nasm
  - script: |
      wget https://github.com/mozilla/mozjpeg/archive/${MOZJPEG_VERSION_IDENTIFIER}.tar.gz -O mozjpeg-${MOZJPEG_VERSION}.tar.gz
      tar xvf mozjpeg-${MOZJPEG_VERSION}.tar.gz
    displayName: Download sources
  - script: |
      cd mozjpeg-${MOZJPEG_VERSION}
      autoreconf -fiv
      cd ..
      sh mozjpeg-${MOZJPEG_VERSION}/configure --prefix=${BUILD_ARTIFACTSTAGINGDIRECTORY}/mozjpeg/$RID --host=$TARGET
      make
    displayName: Build
  - script: |
      make install
    displayName: Install
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/mozjpeg' 
      artifactName: 'mozjpeg' 
      publishLocation: 'Container'
    displayName: Publish

- job: pack
  dependsOn:
    - native_windows
    - native_macos
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: build/templates/build.yml
  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      packagesToPack: '$(SrcDir)/MozJpegSharp/MozJpegSharp.csproj'
      configuration: $(BuildConfiguration)
      packDirectory: $(Build.ArtifactStagingDirectory)/MozJpegSharp
      arguments: '--no-restore --no-build'
    displayName: 'Pack'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/MozJpegSharp'
      artifactName: 'nuget'
      publishLocation: 'Container'
    displayName: Publish
  
- job: test_windows
  dependsOn:
    - native_windows
    - native_macos
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: build/templates/build.yml
  - script: |
      set PATH=%PATH%;%SYSTEM_ARTIFACTSDIRECTORY%\mozjpeg\win7-x64\bin\
      echo %PATH%
    displayName: Append native lib dir to path
  - template: build/templates/test.yml

- job: test_macos
  dependsOn:
    - native_windows
    - native_macos
  pool:
    vmImage: 'macOS-10.15'
  variables:
    RID: osx-x64
  steps:
  - script: |
      brew install mono-libgdiplus
    displayName: Install libgdiplus
  - template: build/templates/build.yml
  - script: |
      export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${SYSTEM_ARTIFACTSDIRECTORY}/mozjpeg/${RID}/lib/
      echo $LD_LIBRARY_PATH
    displayName: Append native lib dir to path
  - template: build/templates/test.yml

- job: test_ubuntu_18_04
  condition: eq(1,2) # disable as there currently is no mozjpeg easily available
  dependsOn:
    - native_windows
    - native_macos
  variables:
    RID: ubuntu.18.04-x64
  pool:
    vmImage: 'ubuntu-16.04'
  container:
    image: mcr.microsoft.com/dotnet/core/sdk:3.0-bionic
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
  steps:
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: Set up sudo
  - script: |
      sudo add-apt-repository ppa:quamotion/ppa
      sudo apt-get update
      sudo apt-get install -y libc6-dev libgdiplus libcurl4 libturbojpeg
    displayName: Install libgdiplus, libcurl
  - template: build/templates/build.yml
  - template: build/templates/test.yml

- job: test_centos_7
  dependsOn:
    - native_windows
    - native_macos
  variables:
    RID: centos.7-x64
  pool:
    vmImage: 'ubuntu-16.04'
  container:
    image: centos:7
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
  steps:
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "yum install -y sudo"
    displayName: Set up sudo
  - script: |
      sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
      # Work around https://github.com/dotnet/core/issues/3853
      sudo yum install -y https://packages.microsoft.com/centos/7/prod/netstandard-targeting-pack-2.1.0-x64.rpm
      sudo yum install -y dotnet-sdk-3.0
    displayName: Install .NET 3.0 SDK
  - script: |
      sudo yum-config-manager -y --add-repo https://download.opensuse.org/repositories/home:/qmfrederik/CentOS_7/home:qmfrederik.repo
      sudo yum-config-manager -y --add-repo https://download.opensuse.org/repositories/home:/caoli5288:/mozjpeg/CentOS_7/home:caoli5288:mozjpeg.repo
      sudo yum install -y libgdiplus mozjpeg
    displayName: Install mozjpeg native binaries
  - template: build/templates/build.yml
  - template: build/templates/test.yml