trigger:
  batch: true
  branches:
    include:
    - "*"

variables:
  - template: build/vars.yml

stages:
- template: build/stages/buildnativelibs.yml

- template: build/stages/test.yml
  parameters:
    appendNativeLibPath: true
    dependsOn: BuildNativeLibs


- template: build/stages/packnative.yml
  parameters:
    dependsOn: BuildNativeLibs

- template: build/stages/deploy.yml
