trigger:
  batch: true
  branches:
    include:
    - "*"

variables:
  - template: build/vars.yml

stages:
###################
###### TESTS ######
###################
- template: build/stages/test.yml

###################
###### PACK ######
###################
- template: build/stages/pack.yml

##################
##### DEPLOY #####
##################
- template: build/stages/deploy.yml
